# Generated by Django 3.1.2 on 2023-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nationalité', models.CharField(max_length=64)),
                ('Filière', models.CharField(max_length=64)),
                ('Identifiant', models.IntegerField()),
                ('Age_bac', models.IntegerField()),
            ],
        ),
    ]
