# Generated by Django 3.1.2 on 2023-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redoublement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulairePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_formulaire', 'Can view Formulaire page')],
            },
        ),
    ]
